# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Esteemator-Pro' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  pod "TextFieldEffects"
  pod 'IQKeyboardManager'
  pod 'BubbleTransition'
  pod 'APESuperHUD'
  pod 'SideMenu' 
end
